version: "3.2"

networks:
  internal:
  external:
    driver: bridge

volumes:
  postgres:
  minio:
  mongodb:

services:
  app:
    image: gabray/tripnjoy_back:latest
    networks:
      - internal
      - external
    depends_on:
      - db
      - mongo
    ports:
      - "8080:8080"
    environment:
      - "spring.datasource.url=jdbc:postgresql://db:5432/postgres"
      - "spring.data.mongodb.host=mongo"
      - "spring.profiles.active=${PROFILE:-default}"

  db:
    image: "postgres:13.6"
    ports:
      - "5432:5432"
    networks:
      - internal
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./sql/db_tripnjoy.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=root"

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb
    networks:
      - internal

  minio:
    image: "quay.io/minio/minio"
    networks:
      - external
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=${MINIO_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}"
    volumes:
      - "minio:/data"